repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: debug-statements
    # -   id: check-docstring-first
        language_version: python3.11

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.1
  hooks:
    - id: ruff
      language_version: python3.11
      args: [ --fix, --exit-non-zero-on-fix ]
