[tool.black]
line-length = 130
target-version = ['py310']

[tool.isort]
line_length = 130
py_version = 310
wrap_length = 10
profile = "black"

[tool.autopep8]
max_line_length = 130
in-place = true
recursive = true
aggressive = 3

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "settings"

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501"]
